### ISSUE TITLE
Unhandled Exception when function called.

### ISSUE THREAD

**Issue by PujanGorg** [awazgyawali/flutter_khalti#1]
This error occurs whenever the "paywithkhalti" button is clicked. I cloned the example repo but the issue persists. Please help fix it.

`E/MethodChannel#flutter_khalti(20261): Failed to handle method call
E/MethodChannel#flutter_khalti(20261): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/MethodChannel#flutter_khalti(20261): 	at android.app.ContextImpl.startActivity(ContextImpl.java:794)
E/MethodChannel#flutter_khalti(20261): 	at android.app.ContextImpl.startActivity(ContextImpl.java:768)
E/MethodChannel#flutter_khalti(20261): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
E/MethodChannel#flutter_khalti(20261): 	at khalti.utils.ActivityUtil.openActivity(Unknown Source)
E/MethodChannel#flutter_khalti(20261): 	at khalti.checkOut.helper.KhaltiCheckOut.show(Unknown Source)
E/MethodChannel#flutter_khalti(20261): 	at com.example.flutterkhalti.FlutterKhaltiPlugin.initKhaltiPayment(FlutterKhaltiPlugin.kt:52)
E/MethodChannel#flutter_khalti(20261): 	at com.example.flutterkhalti.FlutterKhaltiPlugin.onMethodCall(FlutterKhaltiPlugin.kt:31)
E/MethodChannel#flutter_khalti(20261): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#flutter_khalti(20261): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#flutter_khalti(20261): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#flutter_khalti(20261): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_khalti(20261): 	at android.os.MessageQueue.next(MessageQueue.java:324)
E/MethodChannel#flutter_khalti(20261): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter_khalti(20261): 	at android.app.ActivityThread.main(ActivityThread.java:6244)
E/MethodChannel#flutter_khalti(20261): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_khalti(20261): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
E/MethodChannel#flutter_khalti(20261): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
E/flutter (20261): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?, null)
E/flutter (20261): #0      StandardMethodCodec.decodeEnvelope 
E/flutter (20261): #1      MethodChannel.invokeMethod 
E/flutter (20261): <asynchronous suspension>
E/flutter (20261): #2      FlutterKhalti.initPayment
E/flutter (20261): #3      _CartScreenState._payViaKhalti
E/flutter (20261): #4      _CartScreenState.build.<anonymous closure>
E/flutter (20261): #5      _InkResponseState._handleTap 
E/flutter (20261): #6      _InkResponseState.build.<anonymous closure> 
E/flutter (20261): #7      GestureRecognizer.invokeCallback 
E/flutter (20261): #8      TapGestureRecognizer._checkUp 
E/flutter (20261): #9      TapGestureRecognizer.handlePrimaryPointer 
E/flutter (20261): #10     PrimaryPointerGestureRecognizer.handleEvent 
E/flutter (20261): #11     PointerRouter._dispatch 
E/flutter (20261): #12     PointerRouter.route 
E/flutter (20261): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
E/flutter (20261): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
E/flutter (20261): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
E/flutter (20261): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
E/flutter (20261): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
E/flutter (20261): #18     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter (20261): #19     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (20261): #20     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (20261): #21     _invoke1  (dart:ui/hooks.dart:233:10)
E/flutter (20261): #22     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)
`

**Comment by sawin0** [comment]
Hello @PujanGorg I hope this example will fix your problem.
https://github.com/sawin0/flutter-khalti_example

**Comment by awazgyawali** [comment]
Fixed at 0.3.0 https://github.com/awazgyawali/flutter_khalti/pull/3
